WindowsAuth/Controllers/PeriodicasJsonController.cs
using FollowTaskIt.AccesoBaseDatosV2;
using FollowTaskIt.Enumeradores;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FollowTaskIt.Presentacion.Controllers
{
    public class PeriodicasJsonController : BaseJsonController
    {
        [HttpPost]
        [OutputCache(Duration = 10, VaryByParam = "*")]
        public JsonResult Listado(int jtStartIndex = 0, int jtPageSize = 99, string jtSorting = "", int reunionId = 0, string searchString = "")
        {
            try
            {
                var reunion = db.REUNION.Find(reunionId);
                var listado = reunion.TAREAS_PERIODICAS.Select(a => new
                {
                    reunionId = a.reunionId,
                    tareaperiodicaId = a.tareaperiodicaId,
                    empleadoId = a.empleadoId,
                    nombre = a.EMPLEADOS.nombre,
                    tarea = a.tarea,
                    proxima_ejecucion = a.proxima_ejecucion,
                    Activa = a.Activa,
                    PeriodoId = a.PeriodoId,
                    DiaId = a.DiaId
                });

                return Json(new { Result = "OK", Records = listado.OrderBy(orden => orden.nombre).Skip(jtStartIndex).Take(jtPageSize), TotalRecordCount = listado.Count() });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
        [HttpPost]
        public JsonResult Create(TAREAS_PERIODICAS periodica)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return Json(new { Result = "ERROR", Message = "Form is not valid! Please correct it and try again." });
                }
                if (periodica.proxima_ejecucion == null) {
                    periodica.proxima_ejecucion = DateTime.Now;
                }
                if (periodica.proxima_ejecucion < DateTime.Now)
                {
                    return Json(new { Result = "ERROR", Message = "La fecha de la proxima ejecucion no puede ser menor a la fecha actual." });
                }
                periodica.Activa = true;
                periodica.fechaInsertar = (periodica.proxima_ejecucion).AddDays(CantidadDias.InsertarPeriodicas);
                periodica.AuditoriaCrear(User.Identity.Name.ToString());
                db.TAREAS_PERIODICAS.Add(periodica);
                db.PARAMETROS.FirstOrDefault().TareaPeriodicaEjecutada = null;
                db.SaveChanges();
                var tempPeriodica = new TAREAS_PERIODICAS();
                tempPeriodica.empleadoId = periodica.empleadoId;
                tempPeriodica.proxima_ejecucion = periodica.proxima_ejecucion;
                tempPeriodica.reunionId = periodica.reunionId;
                tempPeriodica.tarea = periodica.tarea;
                tempPeriodica.PeriodoId = periodica.PeriodoId;
                tempPeriodica.DiaId = periodica.DiaId;
                tempPeriodica.Activa = true;
            

                return Json(new { Result = "OK", Record = tempPeriodica });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
        [HttpPost]
        public JsonResult Update(TAREAS_PERIODICAS periodica)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return Json(new { Result = "ERROR", Message = "Form is not valid! Please correct it and try again." });
                }
                if (periodica.proxima_ejecucion == null)
                {
                    periodica.proxima_ejecucion = DateTime.Now;
                }
                if (periodica.proxima_ejecucion < DateTime.Now)
                {
                    return Json(new { Result = "ERROR", Message = "La fecha de la proxima ejecucion no puede ser menor a la fecha actual." });
                }
                var objPeriodica = db.TAREAS_PERIODICAS.Find(periodica.tareaperiodicaId);
                objPeriodica.empleadoId = periodica.empleadoId;
                objPeriodica.tarea = periodica.tarea;
                objPeriodica.Activa = periodica.Activa;
                objPeriodica.proxima_ejecucion = periodica.proxima_ejecucion;
                objPeriodica.PeriodoId = periodica.PeriodoId;
                objPeriodica.DiaId = periodica.DiaId;
                objPeriodica.fechaInsertar = (objPeriodica.proxima_ejecucion).AddDays(CantidadDias.InsertarPeriodicas);
                objPeriodica.AuditoriaEditar(User.Identity.Name.ToString());
                db.SaveChanges();
                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
        [HttpPost]
        public JsonResult Delete(int tareaperiodicaId)
        {
            try
            {
                var eliminarPeriodica = db.TAREAS_PERIODICAS.Find(tareaperiodicaId);
                db.TAREAS_PERIODICAS.Remove(eliminarPeriodica);
                db.SaveChanges();
                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
        public JsonResult GetPeriodosOptions()
        {
            try
            {
                var periodos = db.Periodos.Where(p => p.Activo == true).OrderBy(p => p.Orden).Select(c => new { DisplayText = c.Descripcion, Value = c.PeriodoId }).OrderBy(p => p.DisplayText);

                return Json(new { Result = "OK", Options = periodos });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
        public JsonResult GetDiasOptions(int PeriodoId = 0)
        {
            try
            {
                if (PeriodoId > 0)
                {
                    var otro1 = db.Dias.Where(p => p.Activo == true && p.PeriodoId == PeriodoId).OrderBy(p => p.Orden).Select(c => new { DisplayText = c.Nombre, Value = c.DiaId });
                    return Json(new { Result = "OK", Options = otro1 });
                }
                else
                {
                    var otro2 = db.Dias.Where(p => p.Activo == true).OrderBy(p => p.Orden).Select(c => new { DisplayText = c.Nombre, Value = c.DiaId });
                    return Json(new { Result = "OK", Options = otro2 });
                }

            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

    }
}

WindowsAuth/Controllers/TareasJsonController.cs
using FollowTaskIt.AccesoBaseDatosV2;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FollowTaskIt.Presentacion.Controllers
{
    [Authorize]
    public class TareasJsonController : BaseJsonController
    {
        [HttpPost]
        [OutputCache(Duration = 10, VaryByParam = "*")]
        public JsonResult ListadoEmpleados(int jtStartIndex = 0, int jtPageSize = 99, string jtSorting = "", string empleadoId = "", int minutaId = 0, string searchString = "", bool Id_Check_Realizadas = false, bool Id_Check_NoVencidas = false, bool Id_Check_Vencidas = false, bool Id_Check_SinFecha = false)
        {
            try
            {
                var listadoTareas = getResultadosTareas(jtStartIndex, jtPageSize, jtSorting, empleadoId, Id_Check_Realizadas, Id_Check_NoVencidas, Id_Check_Vencidas, Id_Check_SinFecha, 0, 0, null, null, minutaId);
                var listadoEmpleados = listadoTareas.Select(p => p.EMPLEADOS).ToList().Distinct();
                var listado = listadoEmpleados.Select(a => new
                {
                    tareaId = 0,
                    minutaId = 0,
                    empleadoId = a.empleadoId,
                    nombre = a.nombre,
                    tarea = "",
                    fecha_asignada = DateTime.Now,
                    tareaRecId = 0
                });

                return Json(new { Result = "OK", Records = listado.OrderBy(orden => orden.nombre).Skip(jtStartIndex).Take(jtPageSize), TotalRecordCount = listado.Count() });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
        [HttpPost]
        public JsonResult Create(string tarea, string empleadoId, int minutaId, DateTime? fechaVence, string solicitante = "", bool enviarCodigo = false)
        {
            try
            {
                var esParticipante = db.MINUTA.Find(minutaId).PARTICIPANTES.Where(p => p.empleadoId == empleadoId).Any();
                if (!ModelState.IsValid || String.IsNullOrEmpty(tarea) || String.IsNullOrEmpty(empleadoId) || minutaId == 0 || !esParticipante)
                {
                    return Json(new { Result = "ERROR", Message = "Form is not valid! Please correct it and try again." });
                }
                if (fechaVence != null && fechaVence < DateTime.Now)
                {
                    return Json(new { Result = "ERROR", Message = "No puede agregarse porque la fecha es menor al dia de hoy." });
                }
                string usuario = "";
                string usuario_nombre = "";
                if (String.IsNullOrEmpty(solicitante))
                {
                    usuario = User.Identity.Name.ToString();
                    usuario_nombre = (from data in db.EMPLEADOS where data.usuario == usuario select data.nombre).FirstOrDefault();
                }
                else if (enviarCodigo)
                {
                    usuario_nombre = (from data in db.EMPLEADOS where data.empleadoId == solicitante select data.nombre).FirstOrDefault();
                }
                if (!String.IsNullOrEmpty(usuario_nombre))
                {
                    solicitante = usuario_nombre;
                }
                var nuevaTarea1 = new TAREAS();
                nuevaTarea1.empleadoId = empleadoId;
                nuevaTarea1.tarea = tarea;
                nuevaTarea1.minutaId = minutaId;
                nuevaTarea1.solicitante = solicitante;
                nuevaTarea1.fecha_asignada = DateTime.Now;
                nuevaTarea1.Realizada = false;
                if (fechaVence != null)
                {
                    var nuevaRefecha = new REFECHAS();
                    nuevaRefecha.Fecha = (DateTime)fechaVence;
                    nuevaRefecha.activa = true;
                    nuevaTarea1.REFECHAS.Add(nuevaRefecha);
                    nuevaTarea1.fecha_vence = fechaVence;
                }
                db.TAREAS.Add(nuevaTarea1);
                var nuevaTarea = new TAREAS();
                nuevaTarea.empleadoId = empleadoId;
                nuevaTarea.tarea = tarea;
                nuevaTarea.minutaId = minutaId;
                nuevaTarea.solicitante = solicitante;
                nuevaTarea.fecha_asignada = DateTime.Now;
                nuevaTarea.Realizada = false;
                nuevaTarea.fecha_vence = fechaVence;

                db.SaveChanges();
                return Json(new { Result = "OK", Record = nuevaTarea });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
        [HttpPost]
        public JsonResult Delete(int tareaRecId)
        {
            try
            {
                var eliminar = db.TAREAS.Find(tareaRecId);
                db.TAREAS.Remove(eliminar);
                db.SaveChanges();
                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
        [HttpPost]
        [OutputCache(Duration = 10, VaryByParam = "*")]
        public JsonResult ListaParticipantes(int minutaId)
        {
            try
            {
                var listado = db.MINUTA.Find(minutaId).PARTICIPANTES.Select(pp => new { Value = pp.EMPLEADOS.empleadoId, Text = pp.EMPLEADOS.nombre });
                return Json(new { Result = "OK", Records = listado.OrderBy(orden => orden.Text) });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
        [HttpPost]
        public JsonResult ReasignarTareas(string listadoTareas, int minutaId, string empleadoIdHasta, bool conRefechas)
        {
            try
            {
                var _listaConvertir = new List<int>();
                foreach (string item in listadoTareas.Split(';'))
                {
                    int valorSalida = 0;
                    if (int.TryParse(item, out valorSalida))
                    {
                        _listaConvertir.Add(valorSalida);
                    }
                }
                var _tempListadoTareas = db.TAREAS.Where(p => _listaConvertir.Contains(p.tareaRecId));
                foreach (TAREAS ta in _tempListadoTareas)
                {
                    ta.empleadoId = empleadoIdHasta;
                    ta.minutaId = minutaId;
                    if (!conRefechas && ta.REFECHAS.Any())
                    {
                        ta.fecha_vence = null;
                        foreach (REFECHAS re in ta.REFECHAS.ToList())
                        {
                            db.REFECHAS.Remove(re);
                        }
                    }
                }
                db.SaveChanges();
                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
        [HttpPost]
        public JsonResult Update(int tareaRecId, string tarea, bool? Realizada, int? Dias, string Notas, string empleadoId, string hora_ini, string hora_fin)
        {
            try
            {
                bool estaRealizada = false;

                if (!ModelState.IsValid)
                {
                    return Json(new { Result = "ERROR", Message = "Form is not valid! Please correct it and try again." });
                }
                var obj = db.TAREAS.Find(tareaRecId);
                obj.tarea = tarea;
                if (Realizada != null)
                {
                    estaRealizada = (bool)Realizada;
                    obj.Realizada = estaRealizada;
                }
                obj.empleadoId = empleadoId;
                obj.Notas = Notas;
                obj.hora_fin = hora_fin;
                obj.hora_ini = hora_ini;
                if (Dias != null && Dias > 0)
                {
                    DateTime nuevaFechaVence = ((DateTime)obj.fecha_asignada).AddDays((int)Dias);
                    if (nuevaFechaVence > DateTime.Now && nuevaFechaVence > obj.fecha_vence)
                    {
                        obj.fecha_vence = nuevaFechaVence;
                        var objRefecha = obj.REFECHAS.Where(p => p.activa == true).FirstOrDefault();
                        objRefecha.Fecha = nuevaFechaVence;
                    }
                }

                db.SaveChanges();
                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
        [HttpPost]
        [OutputCache(Duration = 10, VaryByParam = "*")]
        public JsonResult Listado(int jtStartIndex = 0, int jtPageSize = 99, string jtSorting = "", string empleadoId = "", int minutaId = 0, string searchString = "", bool Id_Check_Realizadas = false, bool Id_Check_NoVencidas = false, bool Id_Check_Vencidas = false, bool Id_Check_SinFecha = false, bool soloNoRealizadas = false)
        {
            try
            {
                var listadoTareas = getResultadosTareas(jtStartIndex, jtPageSize, jtSorting, empleadoId, Id_Check_Realizadas, Id_Check_NoVencidas, Id_Check_Vencidas, Id_Check_SinFecha, 0, 0, null, null, minutaId, soloNoRealizadas);
                var listado = listadoTareas.Select(a => new
                {
                    minutaId = a.minutaId,
                    tareaId = a.tareaId,
                    tarea = a.tarea,
                    empleadoId = a.empleadoId,
                    fecha_asignada = a.fecha_asignada,
                    fecha_vence = a.fecha_vence,
                    tareaRecId = a.tareaRecId,

WindowsAuth/Views/Meetings/Contador.cshtml
@model FollowTaskIt.Models.EditarContadorViewModel

@{
    ViewBag.Title = Model.Titulo;
}

<h3 class="titulo">@ViewBag.Title</h3>
<hr class="titulo-hr" />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.Minutos, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.TextBoxFor(model => model.Minutos, new { @onkeyup = "changeMinutos()", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Minutos)
            </div>
        </div>

        <hr class="titulo-hr" />
        <div class="form-actions">
            <div class="btn-group" role="group">
                <button id="btnMostrarContador" type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">
                        <i class="fa fa-eye"></i>/<i class="fa fa-eye-slash"></i>
                    </span>
                </button>
            </div>
        </div>
        <div style="clear: both;"></div>

    </div>
}

@if (Request.IsAjaxRequest())
{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/Usuario/jqueryValidationFixToBootStrap.js"></script>
    <script src="~/Scripts/Meetings/MostrarContador.js"></script>
}

WindowsAuth/Views/Meetings/Departamento.cshtml
@model IEnumerable<FollowTaskIt.Models.ListadoTiposDespartamentoViewModel>
<link href="~/Content/morris.css" rel="stylesheet" />
@*<h3 class="titulo">@ViewBag.Title</h3>
<hr class="titulo-hr" />*@
<div class="separacionArriba"></div>
<div class="row">
    @if (Model != null)
    {
        foreach (var reunion in Model)
        {
            <div class="col-lg-3 col-md-6">
                <div class="panel panel-warning">
                    <div class="panel-heading">
                        <div class="row">
                            <dv class="col-xs-3">
                                @Html.Raw(reunion.iconoBoostrap)
                            </dv>
                            <div class="col-xs-9 text-right">
                                <div class="huge">@reunion.contador</div>
                                <div></div>
                            </div>
                        </div>
                    </div>
                    <a href="@Url.Action("Reuniones", "Meetings", new { @id = @reunion.departamentoId, @tipoId = @reunion.tipoId })">
                        <div class="panel-footer">
                            <span class="pull-left">@reunion.Nombre</span>
                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                </div>
            </div>
        }
    }
    else
    {

    }
</div>

WindowsAuth/Views/Meetings/EliminarRefechas.cshtml
@model FollowTaskIt.Models.EliminarRefechasViewModel
@{
    ViewBag.Title = "Desea Eliminar Todas las refechas para?";
}
<h3 class="titulo">@ViewBag.Title</h3>
<hr class="titulo-hr" />
@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "frmEliminarRefecha" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.tareaRecId)

    <div class="form-horizontal">
        @Html.ValidationSummary(true)

        <div class="form-group col-md-12">
            <span> <strong>Reunion</strong></span> @Model.Reunion
        </div>

        <div class="form-group col-md-12">
            <span><strong>Minuta</strong></span> @Model.Minuta
        </div>

        <div class="form-group col-md-12">
            <span><strong>Tarea</strong></span> @Model.Tarea
        </div>

        <div class="form-group">
            <span class="control-label col-md-4"><strong>Confirmar</strong></span> 
            <div class="col-md-8">
                @Html.EditorFor(model => model.Confirmar)
                @Html.ValidationMessageFor(model => model.Confirmar)
            </div>
        </div>

    </div>
    <hr class="titulo-hr" />
    <div class="form-actions">
        <div class="btn-group" role="group">
            <input id="btnEliminarRefecha" type="button" class="btn btn-default" data-dismiss="modal" aria-label="Close" value="Eliminar" />
        </div>
    </div>
    <div style="clear: both;"></div>
}

@if (Request.IsAjaxRequest())
{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/Usuario/jqueryValidationFixToBootStrap.js"></script>
    <script src="~/Scripts/Meetings/EliminarRefechas.js"></script>
    <script>
        $(document).ready(function () {
            $("#btnEliminarRefecha").hide();
            $("#Confirmar").change(function () {
                $("#btnEliminarRefecha").fadeToggle();
            });
        });
    </script>
}
else
{
    @section scripts {
        <script src="~/Scripts/jquery.validate.min.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
        <script src="~/Scripts/Usuario/jqueryValidationFixToBootStrap.js"></script>
        <script src="~/Scripts/Meetings/EliminarRefechas.js"></script>
        <script>
            $(document).ready(function () {
                $("#btnEliminarRefecha").hide();
                $("#Confirmar").change(function () {
                    $("#btnEliminarRefecha").fadeToggle();
                });
            });
        </script>
    }
}

WindowsAuth/Views/Meetings/Periodicas.cshtml
@{
    ViewBag.Title = "Tareas Periodicas de " + ViewBag.nombre;
}

<h3 class="titulo">@ViewBag.Title</h3>

<div class="row">
    <div class="col-lg-12">
        <div id="divContenedorPeriodicas"
             data-url="@Url.Action("", "PeriodicasJson")"
             data-minutaid="@ViewBag.minutaId"
             data-reunionid="@ViewBag.reunionId">
        </div>
    </div>
</div>

@if (Request.IsAjaxRequest())
{
    <script src="~/Scripts/Meetings/Minuta-Periodicas.js"></script>
}

WindowsAuth/Views/Meetings/Reasignacion.cshtml
@{
    ViewBag.Title = "Reasignacion de Tareas ";
}
<link href="~/Content/panelPrimary.css" rel="stylesheet" />
<h3 class="titulo">@ViewBag.Title</h3>
<div class="row">
    <div class="col-md-12">
        <div class="panel with-nav-tabs panel-primary">
            <div class="panel-heading clearfix">
                <div class="pull-left">
                    <h1 class="panel-title pull-left" title="Seleccionar Empleado Desde">
                        <i class="fa fa-user"></i>
                    </h1>
                    <span>
                        @Html.DropDownList("empleadoIdDesde", null, "Seleccionar Empleado Desde", new { @title = "Seleccionar Empleado Desde", @class = "dropDownBarraTitulo2 pull-left" })
                    </span>
                    <h1 class="panel-title pull-left" title="Seleccionar Minuta Hasta">
                        <i class="fa fa-briefcase"></i>
                    </h1>
                    <span>
                        @Html.DropDownList("minutaIdSeleccion", null, "Seleccionar Minuta Hasta", new { @title = "Seleccionar Minuta Hasta", @class = "dropDownBarraTitulo2 pull-left" })
                    </span>
                    <h1 class="panel-title pull-left" title="Seleccionar Empleado Hasta">
                        <i class="fa fa-user"></i>
                    </h1>
                    <span>
                        @Html.DropDownList("empleadoIdHasta", null, "Seleccionar Empleado Hasta", new { @title = "Seleccionar Empleado Hasta", @class = "dropDownBarraTitulo2 pull-left" })
                    </span>
                </div>
                <div class="pull-right">
                    <ul class="nav nav-tabs">
                        @*<li class="active"><a href="#tab1primary" data-toggle="tab">Tareas</a></li>*@
                    </ul>
                </div>
            </div>
            <div class="panel-body">
                <div class="tab-content">
                    <div class="tab-pane fade in active" id="tab1primary">
                        <div class="row">
                            <div class="col-lg-12">
                                <div id="divContenedorReasignacion"
                                     data-url="@Url.Action("", "TareasJson")"
                                     data-minutaid="@ViewBag.minutaId"
                                     data-reunionid="@ViewBag.reunionId">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr class="titulo-hr" />
    <div class="form-actions">
        <div class="btn-group" role="group">
            <button id="btnReasignar" type="button" class="btn btn-default">
                <span>
                    Reasignar
                </span>
            </button>
        </div>
    </div>
    <div style="clear: both;"></div>

</div>


@if (Request.IsAjaxRequest())
{
    <script src="~/Scripts/Meetings/Minuta-Reasignacion.js"></script>
}
else
{

    @section scripts{

        @{
            //Para Usar un Tema de JQuery UI

            //var jQueryStyle = "flick/jquery-ui.flick.min.css";
            //var jQueryStyle = "smoothness/jquery-ui.smoothness.min.css";
            var jQueryStyle = "custom-theme/jquery-ui-1.10.3.custom.css";
            if (!string.IsNullOrEmpty(Request["jQueryStyle"]))
            {
                jQueryStyle = Request["jQueryStyle"];
            }


            //var jTableStyle = "jqueryui/jtable_jqueryui.css";
            var jTableStyle = "lightcolor/blue/jtable.css";
            //jtable/themes/
            //var jTableStyle = "lightcolor/gray/jtable.css";
            //var jTableStyle = "metro/blue/jtable.css";

            //var jTableStyle = "metro/lightgray/jtable.min.css";
            if (!string.IsNullOrEmpty(Request["jTableStyle"]))
            {
                jTableStyle = Request["jTableStyle"];
            }

        }
        <link href="~/Content/jquery.timepicker.css" rel="stylesheet" />
        <script src="~/Scripts/jquery.timepicker.min.js"></script>
        <!-- JTable Control BEGIN -->
        <link href="@Url.Content("~/Content/themes/" + jQueryStyle)" rel="stylesheet" type="text/css" /> @*//Para Usar un Tema de JQuery UI*@
        <link href="@Url.Content("~/Scripts/jtable/themes/" + jTableStyle)" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-ui-1.11.4.min.js")"></script>
        <script type="text/javascript" src="@Url.Content("~/Scripts/jtable/jquery.jtable.js")"></script>
        <script type="text/javascript" src="@Url.Content("~/Scripts/jtable/localization/jquery.jtable.es.js")"></script>
        <!-- JTable Control END -->
        <!-- Mi Codigo -->
        <script src="~/Scripts/Meetings/Minuta-Reasignacion.js"></script>
        <script src="~/Scripts/jquery.validate.min.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
        <script src="~/Scripts/Usuario/jqueryValidationFixToBootStrap.js"></script>
    }

}

<style>
    .anchoModal .ui-dialog {
        width: 758px !important;
    }
</style>