WindowsAuth/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FollowTaskIt.AccesoBaseDatosV2;
using FollowTaskIt.Enumeradores;
using FollowTaskIt.Models;

namespace FollowTaskIt.Presentacion.Controllers
{
    [Authorize]
    public class ServicesController : Controller
    {
        private ModelFollowTaskIt db = new ModelFollowTaskIt();
        private EmailSendController emailSend = new EmailSendController();
        // GET: Services
        public ActionResult Index(int id = 0)
        {
            if (id == 0) { id = 5; }
            ViewBag.Title = "Servicios Solicitados";
            var modelo = new ListadoServiciosViewModel();

            string usuario = User.Identity.Name.ToString();

            string solicitanteId = (from data in db.EMPLEADOS
                                    where data.usuario == usuario
                                    select data.empleadoId).FirstOrDefault();

            modelo.listado = db.SERVICIOS.Where(t => t.solicitanteid == solicitanteId);
            modelo.usuarioLogeado = solicitanteId;
            ViewBag.estadoId = new SelectList(db.SERVICIOS_ESTADOS, "estadoId", "Nombre", id);
            ViewBag.nombreAccion = "Index";
            modelo.listado = modelo.listado.Where(p => p.estadoId == id).ToList();
            modelo.estadoId = id;

            return View(modelo);

        }
        public ActionResult Solicitados(int id = ServiciosEstados.Pendiente)
        {
            ViewBag.Title = "Servicios Solicitados";
            var modelo = new ListadoServiciosViewModel();

            string usuario = User.Identity.Name.ToString();

            string solicitanteId = (from data in db.EMPLEADOS
                                    where data.usuario == usuario
                                    select data.empleadoId).FirstOrDefault();

            modelo.listado = db.SERVICIOS.Where(t => t.solicitanteid == solicitanteId);
            modelo.usuarioLogeado = solicitanteId;
            ViewBag.estadoId = new SelectList(db.SERVICIOS_ESTADOS, "estadoId", "Nombre", id);
            ViewBag.nombreAccion = "Solicitados";
            modelo.listado = modelo.listado.Where(p => p.estadoId == id).ToList();
            modelo.estadoId = id;
            return View("Index", modelo);
        }
        public ActionResult Completados(int id = ServiciosEstados.Completada)
        {
            ViewBag.Title = "Servicios Completados";
            var modelo = new ListadoServiciosViewModel();

            string usuario = User.Identity.Name.ToString();

            string solicitanteId = (from data in db.EMPLEADOS
                                    where data.usuario == usuario
                                    select data.empleadoId).FirstOrDefault();

            modelo.listado = db.SERVICIOS.Where(t => t.solicitanteid == solicitanteId);
            modelo.usuarioLogeado = solicitanteId;
            ViewBag.estadoId = new SelectList(db.SERVICIOS_ESTADOS, "estadoId", "Nombre", id);
            ViewBag.nombreAccion = "Solicitados";
            modelo.listado = modelo.listado.Where(p => p.estadoId == id).ToList();
            modelo.estadoId = id;
            return View("Index", modelo);

        }
        public ActionResult MisServicios(int id = 0)
        {
            if (id == 0) { id = 5; }
            ViewBag.Title = "Mis Servicios Asignados";
            ViewBag.nombreAccion = "MisServicios";
            var modelo = new ListadoServiciosViewModel();

            string usuario = User.Identity.Name.ToString();

            string solicitanteId = (from data in db.EMPLEADOS
                                    where data.usuario == usuario
                                    select data.empleadoId).FirstOrDefault();

            modelo.listado = db.SERVICIOS.Where(t => t.asignadoid == solicitanteId);

            ViewBag.estadoId = new SelectList(db.SERVICIOS_ESTADOS, "estadoId", "Nombre", id);
            modelo.usuarioLogeado = solicitanteId;

            modelo.listado = modelo.listado.Where(p => p.estadoId == id).ToList();
            modelo.estadoId = id;

            return View("Index", modelo);

        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SERVICIOS servicio = db.SERVICIOS.Find(id);
            if (servicio == null)
            {
                return HttpNotFound();
            }
            string usuario = User.Identity.Name.ToString();
            string usuario_empleadoId = (from data in db.EMPLEADOS
                                         where data.usuario == usuario
                                         select data.empleadoId).FirstOrDefault();
            ViewBag.estaAsignado = (servicio.asignadoid == usuario_empleadoId);
            ViewBag.departamentoId = new SelectList(db.DEPARTAMENTO, "departamentoId", "nombre_depto", servicio.departamentoId);
            ViewBag.solicitanteid = new SelectList(db.EMPLEADOS.OrderBy(p => p.nombre), "empleadoId", "nombre", servicio.solicitanteid);
            ViewBag.asignadoid = new SelectList(db.EMPLEADOS.OrderBy(p => p.nombre), "empleadoId", "nombre", servicio.asignadoid);
            ViewBag.estadoId = new SelectList(db.SERVICIOS_ESTADOS, "estadoId", "Nombre", servicio.estadoId);
            ViewBag.tiempoid = new SelectList(db.TIEMPO_STANDARD, "tiempoid", "descripcion", servicio.tiempoid);
            if (Request.IsAjaxRequest())
                return PartialView(servicio);

            return View(servicio);
        }
        public ActionResult Create(int id = 0)
        {
            string currentUser = User.Identity.Name.ToString();
            var objSolicitante = (from data in db.EMPLEADOS
                                  where data.usuario == currentUser
                                  select data).FirstOrDefault();

            SERVICIOS modelo = new SERVICIOS();
            modelo.pcid = System.Environment.MachineName;
            modelo.solicitanteid = objSolicitante.empleadoId;
            if (id == 0)
            {
                modelo.departamentoId = objSolicitante.departamentoId;
            }
            else
            {
                modelo.departamentoId = id;
            }

            modelo.estadoId = ServiciosEstados.Pendiente;
            modelo.fecha = DateTime.Now;
            ViewBag.departamentoId = new SelectList(db.DEPARTAMENTO.Where(p => p.departamentoId == modelo.departamentoId), "departamentoId", "nombre_depto", modelo.departamentoId);
            ViewBag.solicitanteid = new SelectList(db.EMPLEADOS.Where(p => p.empleadoId == modelo.solicitanteid), "empleadoId", "nombre", modelo.solicitanteid);
            ViewBag.asignadoid = new SelectList(db.EMPLEADOS.Where(p => p.Activo == true), "empleadoId", "nombre", modelo.asignadoid);
            ViewBag.estadoId = new SelectList(db.SERVICIOS_ESTADOS, "estadoId", "Nombre", modelo.estadoId);
            ViewBag.tiempoid = new SelectList(db.TIEMPO_STANDARD.Where(p => p.departamentoId == modelo.departamentoId && p.Activo == true), "tiempoid", "descripcion");

            if (Request.IsAjaxRequest())
                return PartialView(modelo);

            return View(modelo);
        }
        public ActionResult Solicitar()
        {
            return View(db.DEPARTAMENTO.Where(a => a.Activo == true && a.Servicios == true));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "servicioId,departamentoId,descripcion,pcid,solicitanteid,fecha,tiempoid,estadoId,solucion,asignadoid,fecha_vence,fecha_cierre,fecha_solucion,notificaciones,satisfaccion")] SERVICIOS modelo)
        {
            if (ModelState.IsValid)
            {

                string currentUser = User.Identity.Name.ToString();
                var objSolicitante = (from data in db.EMPLEADOS
                                      where data.usuario == currentUser
                                      select data).FirstOrDefault();
                var objTiempoStandard = (from p in db.TIEMPO_STANDARD
                                         where p.tiempoid == modelo.tiempoid
                                         select p).FirstOrDefault();
                modelo.asignadoid = objTiempoStandard.empleadoid;
                modelo.fecha_vence = DateTime.Now.AddDays(objTiempoStandard.dias);
                modelo.pcid = System.Environment.MachineName;
                modelo.solicitanteid = objSolicitante.empleadoId;
                modelo.departamentoId = objTiempoStandard.departamentoId;
                modelo.estadoId = ServiciosEstados.Pendiente;
                modelo.fecha = DateTime.Now;
                db.SERVICIOS.Add(modelo);

                try
                {
                    db.SaveChanges();
                    try
                    {
                        emailSend.EnviarCorreoServicioCreado(modelo);
                    }
                    catch (Exception ex)
                    {
                        TempData["MensajeError"] = "error|No se ha podido enviar el correo. Por los siguientes errores: ";
                        TempData["MensajeError"] += ex.Message;
                        if (ex.InnerException != null)
                        {
                            string mensajeErrorInner = ex.InnerException.ToString();
                            if (mensajeErrorInner.Length > 500)
                            {
                                mensajeErrorInner = mensajeErrorInner.Substring(0, 500);
                            }
                            if (mensajeErrorInner.Length > 0)
                            {
                                TempData["MensajeError"] += "<br> Inner Exception: " + mensajeErrorInner;
                            }
                        }

WindowsAuth/Views/Shared/_BreadcrumbPartial.cshtml
<link href="~/Content/font-awesome.3.2.1.css" rel="stylesheet">
<link href="~/Content/breadcrumbStyle.css" rel="stylesheet" />
<div id="breadcrumb_contenedor">
    @*
        <ul id="breadcrumb">
        <li><a href="#"><span class="icon icon-home"> </span></a></li>
        <li><a href="#"><span class="icon icon-beaker"> </span> Projects</a></li>
        <li><a href="#"><span class="icon icon-double-angle-right"></span> Breadcrumb</a></li>
        <li><a href="#"><span class="icon icon-rocket"> </span> Getting started</a></li>
        <li><a href="#"><span class="icon icon-arrow-down"> </span> Download</a></li>
        </ul>
    *@
    @*@Html.Raw(Html.BuildBreadcrumbNavigation())*@
    @*@Html.MvcSiteMap().Menu()*@
    @if (Html.ViewContext.RouteData.Values["controller"].ToString() != "Home")
    {
        @Html.MvcSiteMap().SiteMapPath()
    }
        


</div>

@section scripts{

}

WindowsAuth/Views/Shared/_FlotanteTareaInsertar.cshtml
<div id="divFlotanteTarea" class="dropLinkAbajo">
    <a href="#">
        <span> <i class="fa fa-plus-circle fa-3x"></i> </span>
    </a>
    <div class="dropdown-menu dropLinkAbajoSub">
     
           <div class="row agenda-AsignarTarea">
            <form method="post" id="frmInsert2" novalidate="novalidate">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label" for="empleadoId">Asignado a</label>
                        <div>
                            <select class="form-control" id="empleadoId" name="empleadoId">
                                <option value="">Seleccionar</option>
                                <option value="00002339">ALBA RODRIGUEZ</option>
                                <option value="00002337">ALBERTO PORTELA</option>
                                <option value="00009999">ANDY SANTOS</option>
                                <option value="00003035">ARLENE BENCOSME</option>
                                <option value="10000012">Armando De La Rosa</option>
                                <option value="00002335">CLAUDIA FANDUIZ           </option>
                                <option value="00000629">MANUEL FERMIN           </option>
                                <option value="00001793">MARTIN RODRIGUEZ           </option>
                                <option value="10000006">Nuevo Empleado Softni</option>
                                <option value="10000008">Nuevo Empleado Softni</option>
                                <option value="10000011">Nuevo Empleado Softni3</option>
                                <option value="10000009">Nuevo Empleado Softni4</option>
                                <option value="10000010">Nuevo Empleado Softni6</option>
                                <option value="10000007">Participante Prueba 2</option>
                                <option value="00000509">YANDRA PORTELA           </option>
                            </select>
                            <span class="field-validation-valid" data-valmsg-for="empleadoId" data-valmsg-replace="true"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="solicitante">Solicitante</label>
                        <div>
                            <select class="form-control" id="solicitante" name="solicitante">
                                <option value="">Seleccionar</option>
                                <option value="ALBA RODRIGUEZ">ALBA RODRIGUEZ</option>
                                <option value="ALBERTO PORTELA">ALBERTO PORTELA</option>
                                <option value="ANDY SANTOS">ANDY SANTOS</option>
                                <option value="ARLENE BENCOSME">ARLENE BENCOSME</option>
                                <option value="Armando De La Rosa">Armando De La Rosa</option>
                                <option value="CLAUDIA FANDUIZ           ">CLAUDIA FANDUIZ           </option>
                                <option value="MANUEL FERMIN           ">MANUEL FERMIN           </option>
                                <option value="MARTIN RODRIGUEZ           ">MARTIN RODRIGUEZ           </option>
                                <option value="Nuevo Empleado Softni">Nuevo Empleado Softni</option>
                                <option value="Nuevo Empleado Softni">Nuevo Empleado Softni</option>
                                <option value="Nuevo Empleado Softni3">Nuevo Empleado Softni3</option>
                                <option value="Nuevo Empleado Softni4">Nuevo Empleado Softni4</option>
                                <option value="Nuevo Empleado Softni6">Nuevo Empleado Softni6</option>
                                <option value="Participante Prueba 2">Participante Prueba 2</option>
                                <option value="YANDRA PORTELA           ">YANDRA PORTELA           </option>
                            </select>
                            <span class="field-validation-valid" data-valmsg-for="solicitante" data-valmsg-replace="true"></span>
                        </div>
                    </div>
                </div>
                <div class="col-md-6" style="padding-right: 0px;">
                    <textarea class="text-box multi-line form-control" data-val="true" data-val-required="The textoTarea field is required." id="textoTarea" name="textoTarea"></textarea>
                    <span class="field-validation-valid" data-valmsg-for="textoTarea" data-valmsg-replace="true"></span>
                </div>
                <div class="col-md-1 insertarTarea">
                    <a href="#" id="btnInsertarTarea"><i class="fa fa-check-square fa-3x"></i></a>
                    <div style="clear: both;"></div>
                </div>
              
            </form>
        </div>
   
     </div>
</div>

WindowsAuth/Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
@{
    var modelo = new FollowTaskIt.Models.ViewModelBase();
}
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Company Meetings</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    @*<link href="~/Content/font-awesome.4.4.0.min.css" rel="stylesheet" />*@
    <link href="~/Content/demo.css" rel="stylesheet" />
    <link href="~/Content/footer-distributed-with-address-and-phones.css" rel="stylesheet" />
    @*<link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">*@
</head>
<body data-root="@Url.Content("~")">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Follow Task It", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="body-content">
        @using Microsoft.AspNet.Identity
        @if (Request.IsAuthenticated)
        {
            <div class="row">
                <div class="col-xs-12 col-sm-3 col-md-3 col-lg-2">
                    <div class="panel-group" id="accordion">
                        <div>
                            <div class="panel panel-default panel-heading divContador1" style="display:none; text-align: center;">
                                <div id ="divContador2" style="font-size: 21px; font-weight: 300; line-height: 1.4;"></div>
                            </div>
                        </div>
                        <div class="divContador1" style="display:none; clear:both; margin-bottom: 20px;"></div>
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                                        <span class="glyphicon glyphicon-user"></span>
                                        @Html.ActionLink(" Departamentos", "Index", "FollowTaskIt", null, null)
                                    </a>
                                </h4>
                            </div>
                        </div>
                      
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                                        <span class="glyphicon glyphicon-envelope"></span>
                                        Servicios
                                        <i class="fa fa-fw fa-caret-down"></i>
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseThree" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <table class="table">

                                        <tr>
                                            <td>
                                                <span class="glyphicon glyphicon-search"></span><a href="~/Services/MisServicios"> Mis Servicios</a>
                                                <span class="label label-info"> @modelo.cantidadServicios(User.Identity.GetUserName()) </span>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>
                                                <span class="glyphicon glyphicon-search"></span><a href="~/Services/Solicitados"> Solicitados</a>
                                                <span class="label label-info"> @modelo.cantidadServiciosConsulta(User.Identity.GetUserName()) </span>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>
                                                <span class="glyphicon glyphicon-search"></span><a href="~/Services/Completados"> Completados</a>
                                                <span class="label label-info"> @modelo.cantidadServiciosCompletados(User.Identity.GetUserName()) </span>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>
                                                <span class="glyphicon glyphicon-edit"></span>
                                                @Html.ActionLink(" Solicitar", "Solicitar", "Services")
                                            </td>
                                        </tr>

                                    </table>
                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordion" href="#collapse4">
                                        <span class="glyphicon glyphicon-list-alt"></span>
                                        Consultas
                                        <i class="fa fa-fw fa-caret-down"></i>
                                    </a>
                                </h4>
                            </div>
                            <div id="collapse4" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <table class="table">
                                        <tr>
                                            <td>
                                                <span class="glyphicon glyphicon-search"></span><a href="~/Consultas/Compromisos"> Compromisos</a>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <span class="glyphicon glyphicon-search"></span><a href="~/Consultas/Indicadores"> Indicadores</a>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                        </div>

                        @if (modelo.accesoMantenimiento(User.Identity.GetUserName()))
                        {
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
                                            <span class="glyphicon glyphicon-wrench">
                                            </span> Settings
                                            <i class="fa fa-fw fa-caret-down"></i>
                                        </a>
                                    </h4>
                                </div>
                                <div id="collapseFour" class="panel-collapse collapse">
                                    <div class="panel-body">
                                        <table class="table">
                                            <tr>
                                                <td>
                                                    <span class="glyphicon glyphicon-user"></span> @Html.ActionLink("Empleados", "Index", "Empleados")
                                                </td>
                                            </tr>

                                            <tr>
                                                <td>
                                                    <span class="glyphicon glyphicon-list"></span><a href="~/TipoServicios"> Tipo Servicios</a>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <span class="glyphicon glyphicon-tasks"></span><a href="~/Departamentos">  Departamentos</a>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <span class="glyphicon glyphicon-briefcase"></span><a href="~/Reuniones">  Reuniones</a>
                                                </td>
                                            </tr>
                                            @*<tr>
                                                <td>
                                                    <span class="glyphicon glyphicon-briefcase"></span><a href="~/TiposReuniones">  Tipos Reuniones</a>
                                                </td>
                                            </tr>*@
                                            <tr>
                                                <td>
                                                    <span class="glyphicon glyphicon-hdd"></span><a href="~/Parametros"> Parametros</a>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <span class="glyphicon glyphicon-hdd"></span><a href="~/Dias"> Periodos</a>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        }
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <span class="glyphicon glyphicon-remove"></span>
                                    <a href="javascript:document.getElementById('logoutForm').submit()"> Log off</a>
                                </h4>
                            </div>
                        </div>
                       
                    </div>
                </div>
                <div class="col-xs-12 col-sm-9 col-md-9 col-lg-10 background_logo">
                    <div class="transbox">
                        <div class="padding">
                            @Html.Partial("_BreadcrumbPartial")
                            @RenderBody()
                        </div>
                    </div>
                    @RenderSection("FlotanteTareaInsertar", required: false)
                </div>
            </div>
        }
        else
        {
            @RenderBody()
        }
        <hr />
    </div>
    <footer class="footer-distributed">

        <div class="footer-left">

            @*<img src="@Url.Content("~")Content/images/Logo.png" height="80" width="200" style="opacity:0.9;filter:alpha(opacity=10);" />*@

            <p class="footer-company-name">Company Name&copy; 2016</p>
        
        </div>

        <div class="footer-center">

            <div>
                <i class="fa fa-map-marker"></i>
                <p><span>Your Address</span>Country</p>
            </div>

            <div>
                <i class="fa fa-phone"></i>
                <p>+1 809 999 5555</p>
            </div>

            <div>
                <i class="fa fa-envelope"></i>
                <p><a href="mailto:support@mycompany.com">support@mycompany.com</a></p>
            </div>

        </div>

        <div class="footer-right">

            <p class="footer-company-about">
                <span>Company Name</span>

            </p>

            <div class="footer-icons">

                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-youtube"></i></a>
                <a href="#"><i class="fa fa-internet-explorer"></i></a>

            </div>

        </div>

    </footer>
</body>
</html>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
<script src="~/Scripts/Shared/Layout.js"></script>
<script src="~/Scripts/Usuario/cargarModal.js"></script>
<script src="~/Scripts/Shared/Bootstrap-Notify/bootstrap-notify.min.js"></script>
@if (Request.IsAuthenticated)
{
    <script src="~/Scripts/Shared/NotificacionesEscritorio.js"></script>
}
@RenderSection("scripts", required: false)
@Html.Partial("_ModalTemplate")